version: '2'
services: mysql
   mysql:
      image: mysql:5.6
      container_name: mysql_server
      command: --default-authentication-plugin=mysql_native_password

      # working dir
      volumes: 
        - .:/application
    restart: always
    environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root

    ports:
        - "3306:3306"

    website:
        container_name: php72
        build: 
            context: ./
            dockerfile: Dockerfile
        command: -d
        ports:
            - "80:80"
        volumes:
            - /var/www/html:/var/www/html
        depends_on: 
            - mysql_server

